In [1]:
import numpy as np
import pandas as pd

In [2]:
# load data from Dressel & Farid (2018)
tab = pd.read_csv('./BROWARD_CLEAN_SUBSET.csv')
charge_tab = pd.read_csv('./CHARGE_ID.csv')

In [11]:
tab[tab['juv_fel_count']>0]

,block_num,id,race,sex,age,juv_fel_count,juv_misd_count,priors_count,charge_id,charge_degree (misd/fel),compas_decile_score,two_year_recid
18,1,10307,2,0,31,2,0,6,169,1,6,0
23,1,3398,2,0,21,1,2,3,92,1,10,1
51,2,4943,2,0,46,1,0,9,190,1,9,1
54,2,4977,1,0,39,6,1,17,306,1,7,1
55,2,5765,2,0,51,1,0,19,175,1,9,0
138,3,3510,1,0,36,1,0,10,45,0,9,1
165,4,9933,2,0,27,2,0,14,159,1,10,1
195,4,10700,2,0,36,1,2,14,306,1,10,1
295,6,4907,2,0,31,2,1,16,190,1,9,1
320,7,700,2,0,26,1,1,10,18,1,9,1
340,7,5263,2,0,19,2,1,3,71,1,10,1
384,8,829,1,0,22,1,0,6,306,1,10,1
417,9,5670,1,0,18,5,0,4,58,1,8,1
422,9,1559,1,0,24,1,2,3,45,0,4,0
444,9,9163,2,0,31,1,1,12,337,0,8,1
481,10,5069,2,0,24,1,0,2,326,0,10,1
484,10,10949,2,0,19,1,0,1,190,1,9,1
551,12,603,2,0,29,1,0,2,21,1,5,0
554,12,2543,2,0,37,2,3,24,66,1,8,0
561,12,8308,2,0,27,1,0,6,203,1,7,1
567,12,7987,1,0,29,4,1,10,58,1,9,1
594,12,10935,3,0,31,1,0,7,374,0,9,1
647,13,2519,2,0,32,1,3,24,129,1,7,1
665,14,8140,2,0,31,3,0,16,129,1,10,1
687,14,8354,1,0,29,1,0,9,379,1,8,1
758,16,67,2,0,35,1,0,13,418,1,8,1
770,16,8724,2,0,42,1,0,7,306,1,9,1
863,18,3847,2,0,22,1,0,2,418,1,7,1
880,18,2515,2,0,28,2,1,11,179,1,10,0
907,19,1576,2,0,42,1,0,13,328,0,8,1
911,19,10336,2,0,29,1,0,3,45,0,8,1
921,19,3751,2,0,41,2,0,18,410,0,10,1
997,20,7975,1,0,23,8,2,11,303,1,10,1

In [4]:
c = charge_tab[charge_tab['charge_id'] == 413]
c['mturk_charge_name'].iloc[0]

'Unlicensed Telemarketing'

In [5]:
# dictionary of keys
race = {1:"white", 2:"black",3:"hispanic", 4:"Asian", 5:"Native American", 6:"Other"}
gender = { 0:"male", 1:"female"}
charge_degree = {0: "misdemeanor", 1: "felony"}
recid = {0:"no",1: "yes"}

In [9]:
# randomly select 3 people for initial test
np.random.seed(seed=20) # set the same seed each time so this is repeatable
arr = np.random.randint(size=5,low=0,high=999)
print(arr)
n = 1
for i in arr:
    charge_str = charge_tab[charge_tab['charge_id'] == tab['charge_id'].iloc[i]]['mturk_charge_name'].iloc[0]
    age_str = str(tab['age'].iloc[i])
    deg = charge_degree[tab['charge_degree (misd/fel)'].iloc[i]]
    #print((gender[tab['sex'].iloc[i]],age_str,charge_str))
    #print("The defendant is a %s aged %s. They have been charged with: %s." +\ )
    print('Question '+str(n))
    print("The defendant is a %s aged %s. They have been charged with: %s. This crime is classified as a %s. They have been convicted of %s prior crimes. They have %s juvenile felony charges and %s juvenile misdemeanor charges on their record.\n" % 
          (gender[tab['sex'].iloc[i]],age_str,charge_str,deg,tab['priors_count'].iloc[i],tab['juv_fel_count'].iloc[i],tab['juv_misd_count'].iloc[i]) )
    print("Do you think this person will commit another crime within 2 years? ")
    print(recid[tab['two_year_recid'].iloc[i]])
    print("This person's race is: "+race[tab['race'].iloc[i]])
    print("")
    n = n+1

[355 474 271 223 924]
Question 1
The defendant is a male aged 53. They have been charged with: Driving with a Suspended License. This crime is classified as a felony. They have been convicted of 15 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
yes
This person's race is: black

Question 2
The defendant is a male aged 26. They have been charged with: Battery. This crime is classified as a misdemeanor. They have been convicted of 0 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
no
This person's race is: white

Question 3
The defendant is a male aged 38. They have been charged with: Battery. This crime is classified as a misdemeanor. They have been convicted of 0 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
no
This person's race is: black

Question 4
The defendant is a male aged 61. They have been charged with: Driving with a Suspended License. This crime is classified as a misdemeanor. They have been convicted of 20 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
yes
This person's race is: black

Question 5
The defendant is a male aged 46. They have been charged with: Possession of a Controlled Substance. This crime is classified as a felony. They have been convicted of 2 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
yes
This person's race is: white

In [6]:
# randomly select 20 people
np.random.seed(seed=100) # set the same seed each time so this is repeatable
arr = np.random.randint(size=20,low=0,high=999)
print(arr)
n = 1
for i in arr:
    charge_str = charge_tab[charge_tab['charge_id'] == tab['charge_id'].iloc[i]]['mturk_charge_name'].iloc[0]
    age_str = str(tab['age'].iloc[i])
    deg = charge_degree[tab['charge_degree (misd/fel)'].iloc[i]]
    #print((gender[tab['sex'].iloc[i]],age_str,charge_str))
    #print("The defendant is a %s aged %s. They have been charged with: %s." +\ )
    print('Question '+str(n))
    print("The defendant is a %s aged %s. They have been charged with: %s. This crime is classified as a %s. They have been convicted of %s prior crimes. They have %s juvenile felony charges and %s juvenile misdemeanor charges on their record.\n" % 
          (gender[tab['sex'].iloc[i]],age_str,charge_str,deg,tab['priors_count'].iloc[i],tab['juv_fel_count'].iloc[i],tab['juv_misd_count'].iloc[i]) )
    print("Do you think this person will commit another crime within 2 years? ")
    print(recid[tab['two_year_recid'].iloc[i]])
    print("This person's race is: "+race[tab['race'].iloc[i]])
    print("")
    n = n+1

[520 792 835 871 855  79 944 906 350 948 866  53 578 738 526 802 752 280
 655 228]
Question 1
The defendant is a male aged 26. They have been charged with: Burglary. This crime is classified as a felony. They have been convicted of 6 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
yes
This person's race is: black

Question 2
The defendant is a male aged 42. They have been charged with: Possession of Cocaine. This crime is classified as a felony. They have been convicted of 3 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
no
This person's race is: black

Question 3
The defendant is a male aged 23. They have been charged with: Possession of Cannabis/Marijuana. This crime is classified as a misdemeanor. They have been convicted of 2 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
yes
This person's race is: hispanic

Question 4
The defendant is a female aged 27. They have been charged with: Battery. This crime is classified as a misdemeanor. They have been convicted of 0 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
no
This person's race is: black

Question 5
The defendant is a female aged 21. They have been charged with: Forgery. This crime is classified as a felony. They have been convicted of 0 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
no
This person's race is: black

Question 6
The defendant is a male aged 24. They have been charged with: Child Molestation. This crime is classified as a felony. They have been convicted of 2 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
no
This person's race is: hispanic

Question 7
The defendant is a male aged 67. They have been charged with: Battery. This crime is classified as a misdemeanor. They have been convicted of 0 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
no
This person's race is: white

Question 8
The defendant is a male aged 22. They have been charged with: Burglary. This crime is classified as a felony. They have been convicted of 0 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
yes
This person's race is: black

Question 9
The defendant is a male aged 23. They have been charged with: Possession of a Controlled Substance. This crime is classified as a felony. They have been convicted of 6 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
yes
This person's race is: white

Question 10
The defendant is a male aged 26. They have been charged with: Criminal Damage of more than $1000. This crime is classified as a felony. They have been convicted of 3 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
yes
This person's race is: black

Question 11
The defendant is a male aged 41. They have been charged with: Possession of a Controlled Substance. This crime is classified as a felony. They have been convicted of 0 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
yes
This person's race is: white

Question 12
The defendant is a male aged 22. They have been charged with: Possession of Cannabis/Marijuana. This crime is classified as a felony. They have been convicted of 0 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
no
This person's race is: black

Question 13
The defendant is a male aged 24. They have been charged with: Burglary. This crime is classified as a felony. They have been convicted of 0 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
yes
This person's race is: black

Question 14
The defendant is a male aged 26. They have been charged with: Burglary. This crime is classified as a felony. They have been convicted of 5 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
no
This person's race is: black

Question 15
The defendant is a male aged 47. They have been charged with: Possession of Cocaine. This crime is classified as a felony. They have been convicted of 4 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
no
This person's race is: black

Question 16
The defendant is a male aged 31. They have been charged with: Possession of Oxycodone. This crime is classified as a felony. They have been convicted of 17 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
yes
This person's race is: white

Question 17
The defendant is a female aged 32. They have been charged with: Possession of Heroin. This crime is classified as a felony. They have been convicted of 2 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
yes
This person's race is: white

Question 18
The defendant is a male aged 26. They have been charged with: Assault. This crime is classified as a misdemeanor. They have been convicted of 5 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
no
This person's race is: white

Question 19
The defendant is a male aged 52. They have been charged with: Driving Under the Influence. This crime is classified as a misdemeanor. They have been convicted of 15 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
yes
This person's race is: black

Question 20
The defendant is a female aged 53. They have been charged with: Possession of Cocaine. This crime is classified as a felony. They have been convicted of 6 prior crimes. They have 0 juvenile felony charges and 0 juvenile misdemeanor charges on their record.

Do you think this person will commit another crime within 2 years?
yes
This person's race is: white

In [77]:
tab.iloc[arr]

,block_num,id,race,sex,age,juv_fel_count,juv_misd_count,priors_count,charge_id,charge_degree (misd/fel),compas_decile_score,two_year_recid
520,11,8258,2,0,26,0,0,6,55,1,7,1
792,16,4408,2,0,42,0,0,3,306,1,1,0
835,17,1004,3,0,23,0,0,2,283,0,6,1
871,18,9277,2,1,27,0,0,0,45,0,3,0
855,18,8358,2,1,21,0,0,0,418,1,6,0
79,2,9634,3,0,24,0,0,2,212,1,3,0
944,19,10544,1,0,67,0,0,0,45,0,1,0
906,19,6805,2,0,22,0,0,0,59,1,3,1
350,8,8045,1,0,23,0,0,6,297,1,9,1
948,19,2128,2,0,26,0,0,3,90,1,3,1
866,18,8205,1,0,41,0,0,0,253,1,2,1
53,2,1103,2,0,22,0,0,0,246,1,8,0
578,12,1943,2,0,24,0,0,0,292,1,3,1
738,15,9136,2,0,26,0,0,5,60,1,4,0
526,11,1611,2,0,47,0,0,4,306,1,3,0
802,17,6056,1,0,31,0,0,17,319,1,8,1
752,16,9106,1,1,32,0,0,2,354,1,2,1
280,6,7259,1,0,26,0,0,5,31,0,5,0
655,14,2220,2,0,52,0,0,15,128,0,4,1
228,5,6586,1,1,53,0,0,6,306,1,5,1